name: Build API
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build API
        run: ./gradlew build
      - name: Check files
        shell: bash
        run: ls
      - name: Archive build files
        uses: actions/upload-artifact@v2
        with:
          name: API build file
          path: build/**
